### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by EricNebeker** [ucd-library/ezid#8]
@qjhart  I'm getting errors when I try to use the script. For example, trying the login command like this:
ezid login --auth=xxxx:xxxx

I get 

/usr/local/bin/ezid: line 904: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
/usr/local/bin/ezid: line 905: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
/usr/local/bin/ezid: line 907: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
LOG: http --check-status --ssl=ezid --session=ezid --print=ezid --auth= https://ezid.cdlib.org/login
 
I can successfully login with httpie like this:
http GET https://ezid.cdlib.org/login --auth xxxx:xxxx

**Comment by qjhart** [comment]
Fixed in e66dd69770cb5b9f5f4cb4f69e49bab125d06d90
